name: azure_pipelines_storage_master

trigger:
- master

pool:
    name: 'Self Hosted'

stages:
    - stage: BuildandTest
      displayName: Building and Testing Project
      jobs:
          - job: Building
            steps:
                - checkout: self
                  clean: True
                - bash: "exit 1"
    
